### ISSUE TITLE
抓包 退出登录好几次都抓不到

### ISSUE THREAD

**Issue by louavo** [SwaggyMacro/YangLeGeYang#1]

**Comment by HySand** [comment]
Win11打不开，只是生成了一个dll文件，是需要什么依赖吗

**Comment by SwaggyMacro** [comment]
> Win11打不开，只是生成了一个dll文件，是需要什么依赖吗

Win11不清楚了，我这也没有机器测试，理论上来说应该没问题才对，没有什么依赖（.net 4.7.2 windows也自带）。

**Comment by SwaggyMacro** [comment]
最新的0.2版本不需要抓包了，登陆了游戏自动获取Token。

**Comment by sq800** [comment]
ok。我可能下错了，我下的1.0

**Comment by Jiangdonganxia** [comment]
> > Win11打不开，只是生成了一个dll文件，是需要什么依赖吗
> 
> Win11不清楚了，我这也没有机器测试，理论上来说应该没问题才对，没有什么依赖（.net 4.7.2 windows也自带）。

我W10也不行，用管理员权限也没用

**Comment by SwaggyMacro** [comment]
> > > Win11打不开，只是生成了一个dll文件，是需要什么依赖吗
> > 
> > 
> > Win11不清楚了，我这也没有机器测试，理论上来说应该没问题才对，没有什么依赖（.net 4.7.2 windows也自带）。
> 
> 我W10也不行，用管理员权限也没用

那可能是被杀毒给拦截了之类的吧

**Comment by SwaggyMacro** [comment]
打不开的暂时可以先用v0.1版本，需要自己抓包，明天我再看看什么原因打不开。
https://github.com/SwaggyMacro/YangLeGeYang/releases/tag/0.1

**Comment by Jiangdonganxia** [comment]
> 打不开的暂时可以先用v0.1版本，需要自己抓包，明天我再看看什么原因打不开。 https://github.com/SwaggyMacro/YangLeGeYang/releases/tag/0.1

谢谢大佬

**Comment by sq800** [comment]
我也有报错，把dll文件放到debug文件夹下解决了

**Comment by ahua666** [comment]
0.2版本只生成一个dll  然后vs运行什么也没有  ，打包的exe打开的话就生成这个dll 。我试了java去调用这个dll 控制台提示不是有效的win32位程序 。
![image](https://user-images.githubusercontent.com/84364050/190715687-a744d840-a799-4b54-a2f5-b53f906d6926.png)
![image](https://user-images.githubusercontent.com/84364050/190715885-0c17d37d-b9e2-42cf-aecd-2c44015c5f20.png)
![image](https://user-images.githubusercontent.com/84364050/190716300-cf5026ac-2cd8-4107-9296-87abb3ebd8df.png)

**Comment by SwaggyMacro** [comment]
已知打不开是因为获取不到游戏Token

**Comment by SwaggyMacro** [comment]
一定要等羊了个羊加载完了再打开软件，不然会打不开（具体原因还没找出来）

**Comment by SwaggyMacro** [comment]
OK，v0.3修复了打不开的问题。
下载最新Release即可。
[https://github.com/SwaggyMacro/YangLeGeYang/releases/latest](https://github.com/SwaggyMacro/YangLeGeYang/releases/latest)
