### ISSUE TITLE
助手功能已失效

### ISSUE THREAD

**Issue by jianboy** [SwaggyMacro/YangLeGeYang#12]
只访问
```
v1/game/game_over
```
接口，目前并不能通关，只是 "加入羊群次数" 增加，而"通关次数"依然为0

**Comment by SwaggyMacro** [comment]
加入羊群次数就是指的通关次数，你说的是每日话题通关次数吧？

**Comment by jianboy** [comment]
嗯，“每日话题通关”次数为0

**Comment by SwaggyMacro** [comment]
> 嗯，“每日话题通关”次数为0
> 
> **通关次数应该指的是 “每日话题通关” ，”加入羊群次数“应该指的是尝试过多少次游戏。**
> 
> ![image](https://user-images.githubusercontent.com/11532015/190884373-93b5a8f5-d4dc-426b-a035-8a5c689ddc9e.png)

加入羊群次数是通关次数，每日话题通关是分开的。

**Comment by SwaggyMacro** [comment]
加入羊群次数就是在朋友圈历史排行榜上显示的通关次数

**Comment by SwaggyMacro** [comment]
v0.4 更新了话题通关次数了，相关代码也已经上传。
