### ISSUE TITLE
不好用了现在

### ISSUE THREAD

**Issue by Lxc5211314** [SwaggyMacro/YangLeGeYang#16]

**Comment by SwaggyMacro** [comment]
![image](https://user-images.githubusercontent.com/38845682/190946007-09992fd8-f04a-4424-8d37-77d91c7d745b.png)
正常使用

**Comment by SwaggyMacro** [comment]
2022-09-19 11:40 测试正常
![image](https://user-images.githubusercontent.com/38845682/190946082-810cb018-0d7f-4553-912e-f2860f2d5b5d.png)
