### ISSUE TITLE
点击羊它后排行榜还是显示0

### ISSUE THREAD

**Issue by swshuji** [SwaggyMacro/YangLeGeYang#17]
![image](https://user-images.githubusercontent.com/44913105/190970922-d8892bc2-48de-4170-91c8-5cfa0a4b01be.png)

**Comment by SwaggyMacro** [comment]
可能是羊了个羊服务器卡了 排行榜没获取到或者没刷新

**Comment by SwaggyMacro** [comment]
已更新v0.5版本 目前使用正常。
[https://github.com/SwaggyMacro/YangLeGeYang/releases/download/0.5/SheepSheep.exe](https://github.com/SwaggyMacro/YangLeGeYang/releases/download/0.5/SheepSheep.exe)
