### ISSUE TITLE
现在好像通过次数没有用了

### ISSUE THREAD

**Issue by WuZhiChuXin** [SwaggyMacro/YangLeGeYang#18]

**Comment by SwaggyMacro** [comment]
可能羊了个羊那边服务器出问题了或者修复了，可以先等一下

**Comment by jimmyczm** [comment]
api变了
https://github.com/Lcry/a-sheep-assistant/issues/108

**Comment by SwaggyMacro** [comment]
已更新v0.5版本 目前使用正常。
[https://github.com/SwaggyMacro/YangLeGeYang/releases/download/0.5/SheepSheep.exe](https://github.com/SwaggyMacro/YangLeGeYang/releases/download/0.5/SheepSheep.exe)
