### ISSUE TITLE
请问那个助手在哪下

### ISSUE THREAD

**Issue by 3Dieji** [SwaggyMacro/YangLeGeYang#19]

**Comment by SwaggyMacro** [comment]
[https://github.com/SwaggyMacro/YangLeGeYang/releases/download/0.5/SheepSheep.exe](https://github.com/SwaggyMacro/YangLeGeYang/releases/download/0.5/SheepSheep.exe)

**Comment by 3Dieji** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月19日(星期一) 晚上6:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SwaggyMacro/YangLeGeYang] 请问那个助手在哪下 (Issue #19)





 
https://github.com/SwaggyMacro/YangLeGeYang/releases/download/0.5/SheepSheep.exe
