### ISSUE TITLE
失效了，只能通关话题了现在

### ISSUE THREAD

**Issue by v835845728** [SwaggyMacro/YangLeGeYang#27]
失效了，只能通关话题了现在

**Comment by SwaggyMacro** [comment]
接口均已失效，但还有两个思路:
1. 直接修改内存，让第二关卡片数量减少，或直接通关，可以再用通关后的信息构造请求体（似乎无效）。
2. 获取卡片图层信息，写算法计算出最优解。（但不太可能，基本上都是死局。）
3. 实在不行单纯只写图层透视

但官方似乎已经限制了每日通关次数，好像变得没太大必要了。
有空就尽量更新。

**Comment by SwaggyMacro** [comment]
已修复加入羊群，但刷的速度会慢一下。
