### ISSUE TITLE
加入不了羊群，通过次数就成功显示

### ISSUE THREAD

**Issue by Z-kawa** [SwaggyMacro/YangLeGeYang#30]

**Comment by SwaggyMacro** [comment]
已经想到办法，测试过可以刷了，正在实现代码中

**Comment by DarkAsm** [comment]
> 已经想到办法，测试过可以刷了，正在实现代码中

6666666666

**Comment by lcfw-1997** [comment]
> 
大概是什么方式通关加入羊群？

**Comment by lcfw-1997** [comment]
> 代码已经重获办法，测试过可以刷了，正在实现中

大概是什么方式通关并加入羊群？

**Comment by ShaoNian-jzp** [comment]
> 代码已经重获办法，测试过可以刷了，正在实现中

>比心

**Comment by Charliego93** [comment]
看到代码已经提交了，release？无法自动获取token，在手机上抓包后手动输入也是可以的吧？

**Comment by SwaggyMacro** [comment]
> 看到代码已经提交了，release？无法自动获取token，在手机上抓包后手动输入也是可以的吧？

手动抓包也可以，如果PC不能自动获取Token的话请更新电脑版微信。

**Comment by SwaggyMacro** [comment]
已修复加入羊群，但刷的速度会慢一下。

**Comment by Charliego93** [comment]
> > 看到代码已经提交了，release？无法自动获取token，在手机上抓包后手动输入也是可以的吧？
> 
> 手动抓包也可以，如果PC不能自动获取Token的话请更新电脑版微信。

已看到更新，辛苦💦
