### ISSUE TITLE
PC端小程序老是刷新不出来是怎么肥事

### ISSUE THREAD

**Issue by zoudingyi** [SwaggyMacro/YangLeGeYang#34]
你们wechat是什么版本的？

**Comment by SwaggyMacro** [comment]
刷不出来可以尝试安装一下最新版本微信：[https://windows.weixin.qq.com/](https://windows.weixin.qq.com/?lang=zh_HK)
也有可能是羊了个羊服务器卡了

**Comment by zoudingyi** [comment]
> 刷不出来可以尝试安装一下最新版本微信：[https://windows.weixin.qq.com/](https://windows.weixin.qq.com/?lang=zh_HK) 也有可能是羊了个羊服务器卡了

已经是最新版了 哭死 等会儿晚点再试试。

**Comment by SwaggyMacro** [comment]
> > 刷不出来可以尝试安装一下最新版本微信：[https://windows.weixin.qq.com/](https://windows.weixin.qq.com/?lang=zh_HK) 也有可能是羊了个羊服务器卡了
> 
> 已经是最新版了 哭死 等会儿晚点再试试。

需要你打开羊了个羊小程序，授权微信信息后才能获取到的（不知道怎么操作可以直接点击 加入羊群 进入游戏就会要求授权）。
