### ISSUE TITLE
下载以后打不开

### ISSUE THREAD

**Issue by cct668** [SwaggyMacro/YangLeGeYang#38]
下载以后打不开

**Comment by SwaggyMacro** [comment]
有没有什么提示，有的话麻烦截图发一下。
没有的话大几率是被杀毒软件之类的拦截了。

**Comment by cct668** [comment]
什么提示都没有，双击以后啥都没




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月21日(星期三) 晚上10:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SwaggyMacro/YangLeGeYang] 下载以后打不开 (Issue #38)





 
有没有什么提示，有的话麻烦截图发一下。
 没有的话大几率是被杀毒软件之类的拦截了。

**Comment by SwaggyMacro** [comment]
那可能是被杀毒软件之类的拦截了，我们这没问题。

**Comment by cct668** [comment]
ok，好吧，谢谢啦，不会是我没C#环境啥的问题吧





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月21日(星期三) 晚上10:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SwaggyMacro/YangLeGeYang] 下载以后打不开 (Issue #38)





 
那可能是被杀毒软件之类的拦截了，我们这没问题。

**Comment by cct668** [comment]
已解决，楼主66666，非常感谢
