### ISSUE TITLE
大佬，游戏又更新了，工具不能用了

### ISSUE THREAD

**Issue by sendylian** [SwaggyMacro/YangLeGeYang#39]

**Comment by Moyahito** [comment]
我们可以等待更新

**Comment by fongfong712** [comment]
用軟件得到token後用這個刷https://y.bi8bo.cn/,我剛試OK

**Comment by SwaggyMacro** [comment]
可能是羊了个羊服务器问题或者网络问题吧，目前身边没有电脑，但有网友14:58时测试可用。![Screenshot_2022-09-22-18-43-12-085_com.android.chrome.jpg](https://user-images.githubusercontent.com/38845682/191727274-a034a687-1654-46d8-b811-ad8dbf305a1d.jpg)

**Comment by SwaggyMacro** [comment]
18:50 测试可用

![309f0d5cd9a8e3ed.jpg](https://user-images.githubusercontent.com/38845682/191728078-4f2a9bf1-2a72-4f73-9fdc-8a20cc5e497f.jpg)
![Screenshot_2022-09-22-18-48-21-629_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/38845682/191728098-40aacf02-3d79-41ea-9aa7-b8cb361dac85.jpg)
