### ISSUE TITLE
感谢楼主的token获取软件，curl已写好，楼主改exe吧，不过不知道什么时候失效

### ISSUE THREAD

**Issue by ganchu** [SwaggyMacro/YangLeGeYang#44]
https://www.apifox.cn/apidoc/shared-2ee360c3-e0c7-40b1-bf71-7ab55b3a17ee/api-41330646

**Comment by qiuapeng921** [comment]
> https://www.apifox.cn/apidoc/shared-2ee360c3-e0c7-40b1-bf71-7ab55b3a17ee/api-41330646

老哥来个微信 让我加下

**Comment by zuoFeng59556** [comment]
不错，很厉害

**Comment by zuoFeng59556** [comment]
> https://www.apifox.cn/apidoc/shared-2ee360c3-e0c7-40b1-bf71-7ab55b3a17ee/api-41330646

每次请求只能加入一次吗，可以设置完成次数吗
