### ISSUE TITLE
有后门自己掂量着办

### ISSUE THREAD

**Issue by kalivim** [SwaggyMacro/YangLeGeYang#7]
![1006DA44-8010-454A-A6EE-CFF66DC08B9F](https://user-images.githubusercontent.com/20452577/190837494-f989625c-cfdd-46fd-9165-abba4d20e315.jpeg)

**Comment by SwaggyMacro** [comment]
这是易语言编译出来的dll报的毒，你可以自行编译dll调用。
[main.zip](https://github.com/SwaggyMacro/YangLeGeYang/files/9590790/main.zip)

**Comment by kalivim** [comment]
源码自己编译吧

**Comment by SwaggyMacro** [comment]
> 源码自己编译吧

自己编译也是一样的，报毒的是调用的DLL，因为C#无法操作非托管进程内存，只能借助其他语言。

**Comment by SwaggyMacro** [comment]
使用C#实现了这部分报毒的DLL了，之前用易语言写的DLL，现在应该没事了，重新git clone本项目就可以看到实现代码了，在WxToken.cs中。
