### ISSUE TITLE
今天获取不到t了

### ISSUE THREAD

**Issue by huanyue6660** [SwaggyMacro/YangLeGeYang#8]

**Comment by SwaggyMacro** [comment]
v0.3版本? 
我这正常，重新登陆微信试试。

**Comment by huanyue6660** [comment]
PC最新版本微信

**Comment by SwaggyMacro** [comment]
> PC最新版本微信

最新版本软件：[https://github.com/SwaggyMacro/YangLeGeYang/releases/latest](https://github.com/SwaggyMacro/YangLeGeYang/releases/latest)
使用教程：[https://github.com/SwaggyMacro/YangLeGeYang#%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B](https://github.com/SwaggyMacro/YangLeGeYang#%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B)

**Comment by huanyue6660** [comment]
666

**Comment by ahua666** [comment]
这个dll有源码吗，获取token的

**Comment by Yuguochuji** [comment]
要先授权小程序获得你的微信昵称和头像才能获得token

**Comment by SwaggyMacro** [comment]
> 这个dll有源码吗，获取token的

使用C#实现了，重新clone本仓库即可。
